- project:
    templates:
      - openstack-python3-jobs
      - build-openstack-docs-pti
    check:
      jobs:
        - openstack-tox-pep8:
            irrelevant-files:
              - ^doc/.*$
        - openstack-tox-bashate:
            files:
              - ^.*\.sh$
